version: '3'
services:

    nosql:
      image: mongo
      container_name: 'local_mongo'
      restart: always
      environment:
        - MONGO_INITDB_DATABASE=node-api
        - MONGO_USER=local
        - MONGO_PASS=root
      volumes:
        - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
        - ./mongo/volumes:/data/db
      ports:
        - '27017:27017'

    sql:
      image: mysql:8
      container_name: 'local_mysql'
      restart: always
      ports:
          - "33061:3306"
      command: --init-file /data/application/init.sql
      volumes:
          - ./mysql/init.sql:/data/application/init.sql
      environment:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: secret

    redis:
      image: redis:6-alpine
      container_name: 'local_redis'
      restart: always
      ports:
          - "6379:6379"
      command: redis-server
      volumes:
          - ./redis/data:/data
          - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf